const locationTerms = {
  "Автобусн.":          { ua: "",                   en: "Bus",          position: "prefix" },
  "Аеропорт":           { ua: "аероп.",             en: "Airport",      position: "suffix" },
  "Алея":               { ua: "ал.",                en: "Alley",        position: "suffix" },
  "Бульвар":            { ua: "бульв.",             en: "Boulevard",    position: "suffix" },
  "Веломаршрут":        { ua: "Веломаршрут",        en: "Cycle road",   position: "suffix" },
  "Водосховище":        { ua: "вдсх",               en: "Reservoir",    position: "suffix" },
  "Вокзал":             { ua: "в-л",                en: "Station",      position: "suffix" },
  "Станція":            { ua: "ст.",                en: "Station",      position: "suffix" },
  "Селище, хутір":      { ua: "",                   en: "Hamlet",       position: "suffix" },
  "Село":               { ua: "",                   en: "Village",      position: "suffix" },
  "Вулиця":             { ua: "вул.",               en: "Street",       position: "suffix" },
  "Дорога":             { ua: "",                   en: "Road",         position: "suffix" },
  "Залізничн.":         { ua: "",                   en: "Railway",      position: "suffix" },
  "Канал":              { ua: "кан.",               en: "Canal",        position: "suffix" },
  "Лінія":              { ua: "",              en: "Line",         position: "suffix" },
  "Лиман":              { ua: "",                en: "Estuary",          position: "suffix" },
  "Майдан":             { ua: "",             en: "Square",       position: "prefix" },
  "Масив (житловий)":   { ua: "ж/м",                en: "Housing estate",          position: "suffix" },
  "Міська електричка":  { ua: "",  en: "Urban Rail",   position: "prefix" },
  "Місто":              { ua: "",                   en: "City",         position: "suffix" },
  "Міст":               { ua: "м.",                 en: "Bridge",       position: "suffix" },
  "Набережна":          { ua: "наб.",               en: "Embankment",   position: "suffix" },
  "Озеро":              { ua: "оз.",                en: "Lake",         position: "suffix" },
  "Острів":             { ua: "о-в",                en: "Island",       position: "suffix" },
  "Парк":               { ua: "",               en: "Park",         position: "prefix" },
  "Сквер":              { ua: "",              en: "Park",         position: "prefix" },
  "Провулок":           { ua: "пров.",              en: "Lane",         position: "suffix" },
  "Площа":              { ua: "пл.",                en: "Square",       position: "suffix" },
  "Проїзд":             { ua: "пр-д",               en: "Passage",      position: "suffix" },
  "Проспект":           { ua: "просп.",             en: "Avenue",       position: "suffix" },
  "Річка":              { ua: "р.",                 en: "River",        position: "suffix" },
  "Район (житловий)":   { ua: "р-н",                en: "District",          position: "suffix" },
  "Тупик":              { ua: "туп.",               en: "Dead end",     position: "suffix" },
  "Узвіз":              { ua: "уз.",                en: "Descent",      position: "suffix" },
  "Центр міста":        { ua: "Центр міста",              en: "City centre",  position: "suffix" },
  "Шляхопровід":        { ua: "ш-д",                en: "Overpass",     position: "suffix" },
  "Шосе":               { ua: "ш.",                 en: "Highway",      position: "suffix" },
};

export default locationTerms;
