const locationTerms = {
  "Немає":               { ua: "",                 en: "",      position: "suffix" },
  "Автобусн.":          { ua: "",                   en: "bus",          position: "prefix" },
  "Аеропорт":           { ua: "аероп.",             en: "airport",      position: "suffix" },
  "Алея":               { ua: "ал.",                en: "alley",        position: "suffix" },
  "Бульвар":            { ua: "бульв.",             en: "boulevard",    position: "suffix" },
  "Веломаршрут":        { ua: "Веломаршрут",        en: "Сycle road",   position: "suffix" },
  "Водосховище":        { ua: "вдсх",               en: "reservoir",    position: "suffix" },
  "Вокзал":             { ua: "в-л",                en: "station",      position: "suffix" },
  "Станція":            { ua: "ст.",                en: "station",      position: "suffix" },
  "Селище, хутір":      { ua: "",                   en: "hamlet",       position: "suffix" },
  "Село":               { ua: "",                   en: "village",      position: "suffix" },
  "Вулиця":             { ua: "вул.",               en: "street",       position: "suffix" },
  "Дорога":             { ua: "",                   en: "road",         position: "suffix" },
  "Залізничн.":         { ua: "",                   en: "railway",      position: "suffix" },
  "Канал":              { ua: "кан.",               en: "canal",        position: "suffix" },
  "Лінія":              { ua: "",              en: "line",         position: "suffix" },
  "Лиман":              { ua: "",                en: "estuary",          position: "suffix" },
  "Майдан":             { ua: "Майдан",             en: "square",       position: "prefix" },
  "Масив (житловий)":   { ua: "ж/м",                en: "housing estate",          position: "suffix" },
  "Міська електричка":  { ua: "",  en: "urban rail",   position: "prefix" },
  "Місто":              { ua: "",                   en: "city",         position: "suffix" },
  "Міст":               { ua: "м.",                 en: "bridge",       position: "suffix" },
  "Набережна":          { ua: "наб.",               en: "embankment",   position: "suffix" },
  "Озеро":              { ua: "оз.",                en: "lake",         position: "suffix" },
  "Острів":             { ua: "о-в",                en: "island",       position: "suffix" },
  "Парк":               { ua: "Парк",               en: "park",         position: "prefix" },
  "Сквер":              { ua: "Сквер",              en: "park",         position: "prefix" },
  "Провулок":           { ua: "пров.",              en: "lane",         position: "suffix" },
  "Площа":              { ua: "пл.",                en: "square",       position: "suffix" },
  "Проїзд":             { ua: "пр-д",               en: "passage",      position: "suffix" },
  "Проспект":           { ua: "просп.",             en: "avenue",       position: "suffix" },
  "Річка":              { ua: "р.",                 en: "river",        position: "suffix" },
  "Район (житловий)":   { ua: "р-н",                en: "district",          position: "suffix" },
  "Тупик":              { ua: "туп.",               en: "dead end",     position: "suffix" },
  "Узвіз":              { ua: "уз.",                en: "descent",      position: "suffix" },
  "Центр міста":        { ua: "Центр міста",              en: "Сity сentre",  position: "suffix" },
  "Шляхопровід":        { ua: "ш-д",                en: "overpass",     position: "suffix" },
  "Шосе":               { ua: "ш.",                 en: "highway",      position: "suffix" },
};

export default locationTerms;
